'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'
import { useAuth } from '@/contexts/AuthContext'

type Language = 'en' | 'es' | 'fr'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Simple translations object
const translations = {
  en: {
    'app.title': 'Hand - Would a modeling agency hire your hands?',
    'app.description': 'Upload your photos. Get brutally honest AI ratings, expert critiques, and a score out of 100.',
    'home.hero.title': 'Would a modeling agency hire your hands?',
    'home.hero.subtitle': 'Upload your photos. Get brutally honest AI ratings, expert critiques, and a score out of 100.',
    'home.cta.getStarted': 'Get Started →',
    'home.features.title': 'Ready to Face the Truth?',
    'home.features.subtitle': 'Join thousands of people discovering their hand modeling potential',
    'features.title': 'What You Get',
    'features.subtitle': 'Everything you need to know about your hand modeling potential',
    'features.noSugarcoating.title': 'No sugarcoating',
    'features.noSugarcoating.description': 'Only brutal truth.',
    'features.expertFeedback.title': 'Expert feedback',
    'features.expertFeedback.description': 'You\'ll want to share.',
    'features.score.title': 'Score out of 100',
    'features.score.description': 'Compete with yourself.',
    'features.verdict.title': 'Hand-model verdict',
    'features.verdict.description': 'Yes, maybe, or keep your day job.',
    'examples.title': 'See What You\'re Getting Into 👀',
    'examples.subtitle': 'Real examples of our brutally honest feedback',
    'nav.signin': 'Sign In',
    'nav.signup': 'Sign Up',
    'nav.backToHome': 'Back to Home',
    'auth.signin.title': 'Sign in and face the truth about your hands.',
    'auth.signup.title': 'Get your honest hand rating.',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.signinButton': 'Sign In',
    'auth.signingIn': 'Signing In...',
    'auth.signupButton': 'Create Account',
    'auth.signingUp': 'Signing Up...',
    'auth.orContinueWith': 'Or continue with',
    'auth.signinWithGoogle': 'Sign in with Google',
    'auth.signupWithGoogle': 'Sign up with Google',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.learnTruth': 'Learn the truth',
    'auth.signinLink': 'Sign in',
    'auth.getRating': 'Get your honest hand rating and discover what your hands really say about you.',
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.languageDescription': 'Choose your preferred language',
    'settings.accountSettings': 'Account Settings',
    'settings.notifications': 'Notifications',
    'settings.emailUpdates': 'Email Updates',
    'settings.done': 'Done',
    'dashboard.title': 'Hand Rating 👀',
    'dashboard.subtitle': 'Do you have what it takes to be a hand model? Let\'s find out.',
    'dashboard.uploadDescription': 'Upload a photo and get an honest rating. No sugarcoating.',
    'dashboard.mobileTips': '📱 Mobile Tips:',
    'dashboard.mobileTipsDescription': 'Click "Upload Photo" to choose from your gallery or take a new photo with your camera. Make sure your hands are well-lit and clearly visible!',
    'dashboard.dropPhoto': 'Drop your photo here',
    'dashboard.clickToUpload': 'Click to upload your hand photo',
    'dashboard.dragDropOption': 'or drag & drop, or use the button below',
    'dashboard.uploadPhoto': 'Upload Photo',
    'dashboard.chooseFromGallery': 'Choose from Gallery',
    'dashboard.takePhoto': 'Take Photo',
    'dashboard.readyForRating': 'Ready to get your brutally honest rating?',
    'dashboard.analyzing': 'Analyzing...',
    'dashboard.generateResults': 'Generate Results',
    'dashboard.outOf': 'out of 100',
    'dashboard.analysis': '📝 Analysis',
    'dashboard.strengths': '✨ Strengths',
    'dashboard.weaknesses': '⚠️ Weaknesses',
    'dashboard.noStrengths': 'No strengths identified',
    'dashboard.noWeaknesses': 'No weaknesses identified',
    'dashboard.tryAnotherPhoto': '📸 Try Another Photo',
    'dashboard.pleaseSelectFile': 'Please select a file first',
    'dashboard.fileSizeError': 'File size must be less than 10MB',
    'dashboard.invalidFileError': 'Please select an image file',
    'dashboard.signinRequired': 'Please sign in to generate critiques.',
    'dashboard.generationFailed': 'Failed to generate results. Please try again.',
    'profile.dashboard': '🏠 Dashboard',
    'profile.gallery': '🖼️ Gallery',
    'profile.profile': '👤 Profile',
    'profile.settings': '⚙️ Settings',
    'profile.logout': '🚪 Logout',
    'gallery.title': 'Your Gallery',
    'gallery.subtitle': 'View and manage your hand modeling portfolio',
    'gallery.loading': 'Loading Your Gallery...',
    'gallery.loadingDescription': 'Fetching your hand critiques',
    'gallery.error': 'Error Loading Gallery',
    'gallery.tryAgain': '🔄 Try Again',
    'gallery.noPhotos': 'No Photos Yet',
    'gallery.noPhotosDescription': 'Start building your hand modeling portfolio',
    'gallery.uploadFirst': '🚀 Upload First Photo',
    'profile.title': 'Profile Settings',
    'profile.subtitle': 'Manage your account and preferences',
    'profile.backToDashboard': 'Back to Dashboard',
    'profile.viewGallery': '🖼️ View Gallery',
    'profile.accountInfo': 'Account Information',
    'profile.editProfile': '✏️ Edit Profile',
    'profile.displayName': 'Display Name',
    'profile.displayNamePlaceholder': 'Enter your display name',
    'profile.email': 'Email',
    'profile.emailPlaceholder': 'Enter your email',
    'profile.accountType': 'Account Type',
    'profile.googleAccount': 'Google Account',
    'profile.emailPassword': 'Email & Password',
    'profile.notSet': 'Not set',
    'profile.saving': 'Saving...',
    'profile.saveChanges': '💾 Save Changes',
    'profile.cancel': '❌ Cancel',
    'profile.uploadCredits': '📤 Upload Credits',
    'profile.uploadsRemaining': 'Uploads Remaining',
    'profile.uploadsRemainingDesc': 'Uploads you can use anytime',
    'profile.totalUploads': 'Total Uploads Used',
    'profile.totalUploadsDesc': 'All-time upload count',
    'profile.dangerZone': '⚠️ Danger Zone',
    'profile.deleteAccount': 'Delete Account',
    'profile.deleteAccountDesc': 'Permanently remove your account and data',
    'profile.delete': '🗑️ Delete',
    'profile.signOut': 'Sign Out',
    'profile.signOutDesc': 'Sign out from all devices',
    'profile.signOutButton': '🚪 Sign Out',
    'offer.title': 'Get Your Hand Rating',
    'offer.subtitle': 'Professional hand modeling assessment',
    'offer.price': 'for 25 pictures',
    'offer.perPicture': 'That\'s only $0.60 per picture!',
    'offer.whatYouGet': 'What You Get:',
    'offer.scoreOutOf': 'Score out of 100 for each picture',
    'offer.expertFeedback': 'Expert feedback and analysis',
    'offer.improvementTips': 'Improvement tips and suggestions',
    'offer.verdict': 'Hand model potential verdict',
    'offer.unlimitedTime': 'Unlimited time to use credits',
    'offer.processing': 'Processing...',
    'offer.buyFor': 'Buy for $',
    'offer.back': 'Back',
    'offer.warningTitle': '⚠️',
    'offer.warningMessage': 'You have 0 uploads remaining. Purchase more credits to continue.',
    'navbar.dashboard': 'Dashboard',
    'navbar.getCredits': 'Get Credits',
    'navbar.signIn': 'Sign In',
    'navbar.signUp': 'Sign Up',
  },
  es: {
    'app.title': 'Hand - ¿Te contrataría una agencia de modelos para tus manos?',
    'app.description': 'Sube fotos de tus manos. Obtén calificaciones brutalmente honestas de IA, críticas expertas y una puntuación de 100.',
    'home.hero.title': '¿Te contrataría una agencia de modelos para tus manos?',
    'home.hero.subtitle': 'Sube fotos de tus manos. Obtén calificaciones brutalmente honestas de IA, críticas expertas y una puntuación de 100.',
    'home.cta.getStarted': 'Comenzar →',
    'home.features.title': '¿Listo para Enfrentar la Verdad?',
    'home.features.subtitle': 'Únete a miles de personas descubriendo su potencial de modelado de manos',
    'features.title': 'Lo Que Obtienes',
    'features.subtitle': 'Todo lo que necesitas saber sobre tu potencial de modelado de manos',
    'features.noSugarcoating.title': 'Sin endulzar',
    'features.noSugarcoating.description': 'Solo la verdad brutal.',
    'features.expertFeedback.title': 'Comentarios expertos',
    'features.expertFeedback.description': 'Querrás compartirlos.',
    'features.score.title': 'Puntuación de 100',
    'features.score.description': 'Compite contigo mismo.',
    'features.verdict.title': 'Veredicto de modelo de manos',
    'features.verdict.description': 'Sí, tal vez, o mantén tu trabajo diario.',
    'examples.title': 'Mira En Lo Que Te Estás Metiendo 👀',
    'examples.subtitle': 'Ejemplos reales de nuestros comentarios brutalmente honestos',
    'nav.signin': 'Iniciar Sesión',
    'nav.signup': 'Registrarse',
    'nav.backToHome': 'Volver al Inicio',
    'auth.signin.title': 'Inicia sesión y enfrenta la verdad sobre tus manos.',
    'auth.signup.title': 'Obtén tu calificación honesta de manos.',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.emailPlaceholder': 'tu@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.signinButton': 'Iniciar Sesión',
    'auth.signingIn': 'Iniciando Sesión...',
    'auth.signupButton': 'Crear Cuenta',
    'auth.signingUp': 'Registrándose...',
    'auth.orContinueWith': 'O continúa con',
    'auth.signinWithGoogle': 'Iniciar sesión con Google',
    'auth.signupWithGoogle': 'Registrarse con Google',
    'auth.noAccount': '¿No tienes una cuenta?',
    'auth.hasAccount': '¿Ya tienes una cuenta?',
    'auth.learnTruth': 'Aprende la verdad',
    'auth.signinLink': 'Iniciar sesión',
    'auth.getRating': 'Obtén tu calificación honesta de manos y descubre lo que tus manos realmente dicen sobre ti.',
    'settings.title': 'Configuración',
    'settings.language': 'Idioma',
    'settings.languageDescription': 'Elige tu idioma preferido',
    'settings.accountSettings': 'Configuración de Cuenta',
    'settings.notifications': 'Notificaciones',
    'settings.emailUpdates': 'Actualizaciones por Correo',
    'settings.done': 'Listo',
    'dashboard.title': 'Calificación de Manos 👀',
    'dashboard.subtitle': '¿Tienes lo que se necesita para ser modelo de manos? Descubrámoslo.',
    'dashboard.uploadDescription': 'Sube una foto y obtén una calificación honesta. Sin endulzar.',
    'dashboard.mobileTips': '📱 Consejos Móviles:',
    'dashboard.mobileTipsDescription': 'Haz clic en "Subir Foto" para elegir de tu galería o tomar una nueva foto con tu cámara. ¡Asegúrate de que tus manos estén bien iluminadas y claramente visibles!',
    'dashboard.dropPhoto': 'Suelta tu foto aquí',
    'dashboard.clickToUpload': 'Haz clic para subir tu foto de manos',
    'dashboard.dragDropOption': 'o arrastra y suelta, o usa el botón de abajo',
    'dashboard.uploadPhoto': 'Subir Foto',
    'dashboard.chooseFromGallery': 'Elegir de Galería',
    'dashboard.takePhoto': 'Tomar Foto',
    'dashboard.readyForRating': '¿Listo para obtener tu calificación brutalmente honesta?',
    'dashboard.analyzing': 'Analizando...',
    'dashboard.generateResults': 'Generar Resultados',
    'dashboard.outOf': 'de 100',
    'dashboard.analysis': '📝 Análisis',
    'dashboard.strengths': '✨ Fortalezas',
    'dashboard.weaknesses': '⚠️ Debilidades',
    'dashboard.noStrengths': 'No se identificaron fortalezas',
    'dashboard.noWeaknesses': 'No se identificaron debilidades',
    'dashboard.tryAnotherPhoto': '📸 Probar Otra Foto',
    'dashboard.pleaseSelectFile': 'Por favor selecciona un archivo primero',
    'dashboard.fileSizeError': 'El tamaño del archivo debe ser menor a 10MB',
    'dashboard.invalidFileError': 'Por favor selecciona un archivo de imagen',
    'dashboard.signinRequired': 'Por favor inicia sesión para generar críticas.',
    'dashboard.generationFailed': 'Error al generar resultados. Por favor intenta de nuevo.',
    'profile.dashboard': '🏠 Panel de Control',
    'profile.gallery': '🖼️ Galería',
    'profile.profile': '👤 Perfil',
    'profile.settings': '⚙️ Configuración',
    'profile.logout': '🚪 Cerrar Sesión',
    'gallery.title': 'Tu Galería',
    'gallery.subtitle': 'Ve y gestiona tu portafolio de modelado de manos',
    'gallery.loading': 'Cargando Tu Galería...',
    'gallery.loadingDescription': 'Obteniendo tus críticas de manos',
    'gallery.error': 'Error al Cargar Galería',
    'gallery.tryAgain': '🔄 Intentar de Nuevo',
    'gallery.noPhotos': 'Sin Fotos Aún',
    'gallery.noPhotosDescription': 'Comienza a construir tu portafolio de modelado de manos',
    'gallery.uploadFirst': '🚀 Subir Primera Foto',
    'profile.title': 'Configuración de Perfil',
    'profile.subtitle': 'Gestiona tu cuenta y preferencias',
    'profile.backToDashboard': 'Volver al Panel',
    'profile.viewGallery': '🖼️ Ver Galería',
    'profile.accountInfo': 'Información de Cuenta',
    'profile.editProfile': '✏️ Editar Perfil',
    'profile.displayName': 'Nombre de Usuario',
    'profile.displayNamePlaceholder': 'Ingresa tu nombre de usuario',
    'profile.email': 'Correo Electrónico',
    'profile.emailPlaceholder': 'Ingresa tu correo electrónico',
    'profile.accountType': 'Tipo de Cuenta',
    'profile.googleAccount': 'Cuenta de Google',
    'profile.emailPassword': 'Correo y Contraseña',
    'profile.notSet': 'No establecido',
    'profile.saving': 'Guardando...',
    'profile.saveChanges': '💾 Guardar Cambios',
    'profile.cancel': '❌ Cancelar',
    'profile.uploadCredits': '📤 Créditos de Subida',
    'profile.uploadsRemaining': 'Subidas Restantes',
    'profile.uploadsRemainingDesc': 'Subidas que puedes usar en cualquier momento',
    'profile.totalUploads': 'Total de Subidas Usadas',
    'profile.totalUploadsDesc': 'Conteo total de subidas',
    'profile.dangerZone': '⚠️ Zona de Peligro',
    'profile.deleteAccount': 'Eliminar Cuenta',
    'profile.deleteAccountDesc': 'Eliminar permanentemente tu cuenta y datos',
    'profile.delete': '🗑️ Eliminar',
    'profile.signOut': 'Cerrar Sesión',
    'profile.signOutDesc': 'Cerrar sesión de todos los dispositivos',
    'profile.signOutButton': '🚪 Cerrar Sesión',
    'offer.title': 'Obtén Tu Calificación de Manos',
    'offer.subtitle': 'Evaluación profesional de modelado de manos',
    'offer.price': 'por 25 fotos',
    'offer.perPicture': '¡Eso es solo $0.60 por foto!',
    'offer.whatYouGet': 'Lo Que Obtienes:',
    'offer.scoreOutOf': 'Puntuación de 100 para cada foto',
    'offer.expertFeedback': 'Comentarios y análisis expertos',
    'offer.improvementTips': 'Consejos y sugerencias de mejora',
    'offer.verdict': 'Veredicto de potencial de modelo de manos',
    'offer.unlimitedTime': 'Tiempo ilimitado para usar créditos',
    'offer.processing': 'Procesando...',
    'offer.buyFor': 'Comprar por $',
    'offer.back': 'Volver',
    'offer.warningTitle': '⚠️',
    'offer.warningMessage': 'Te quedan 0 subidas. Compra más créditos para continuar.',
    'navbar.dashboard': 'Panel de Control',
    'navbar.getCredits': 'Obtener Créditos',
    'navbar.signIn': 'Iniciar Sesión',
    'navbar.signUp': 'Registrarse',
  },
  fr: {
    'app.title': 'Hand - Une agence vous embaucherait-elle pour vos mains?',
    'app.description': 'Téléchargez des photos de vos mains. Obtenez des évaluations brutalement honnêtes de l\'IA, des critiques d\'experts et un score sur 100.',
    'home.hero.title': 'Une agence vous embaucherait-elle pour vos mains?',
    'home.hero.subtitle': 'Téléchargez des photos de vos mains. Obtenez des évaluations brutalement honnêtes de l\'IA, des critiques d\'experts et un score sur 100.',
    'home.cta.getStarted': 'Commencer →',
    'home.features.title': 'Prêt à Affronter la Vérité?',
    'home.features.subtitle': 'Rejoignez des milliers de personnes découvrant leur potentiel de mannequinat de mains',
    'features.title': 'Ce Que Vous Obtenez',
    'features.subtitle': 'Tout ce que vous devez savoir sur votre potentiel de mannequinat de mains',
    'features.noSugarcoating.title': 'Pas de sucre',
    'features.noSugarcoating.description': 'Seulement la vérité brutale.',
    'features.expertFeedback.title': 'Commentaires d\'experts',
    'features.expertFeedback.description': 'Vous voudrez les partager.',
    'features.score.title': 'Score sur 100',
    'features.score.description': 'Concurrencez-vous.',
    'features.verdict.title': 'Verdict de mannequin de mains',
    'features.verdict.description': 'Oui, peut-être, ou gardez votre travail quotidien.',
    'examples.title': 'Voyez Dans Quoi Vous Vous Engagez 👀',
    'examples.subtitle': 'Vrais exemples de nos commentaires brutalement honnêtes',
    'nav.signin': 'Se Connecter',
    'nav.signup': 'S\'inscrire',
    'nav.backToHome': 'Retour à l\'Accueil',
    'auth.signin.title': 'Connectez-vous et affrontez la vérité sur vos mains.',
    'auth.signup.title': 'Obtenez votre évaluation honnête de mains.',
    'auth.email': 'E-mail',
    'auth.password': 'Mot de Passe',
    'auth.confirmPassword': 'Confirmer le Mot de Passe',
    'auth.emailPlaceholder': 'votre@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.signinButton': 'Se Connecter',
    'auth.signingIn': 'Connexion...',
    'auth.signupButton': 'Créer un Compte',
    'auth.signingUp': 'Inscription...',
    'auth.orContinueWith': 'Ou continuer avec',
    'auth.signinWithGoogle': 'Se connecter avec Google',
    'auth.signupWithGoogle': 'S\'inscrire avec Google',
    'auth.noAccount': 'Vous n\'avez pas de compte ?',
    'auth.hasAccount': 'Vous avez déjà un compte ?',
    'auth.learnTruth': 'Apprenez la vérité',
    'auth.signinLink': 'Se connecter',
    'auth.getRating': 'Obtenez votre évaluation honnête de mains et découvrez ce que vos mains disent vraiment de vous.',
    'settings.title': 'Paramètres',
    'settings.language': 'Langue',
    'settings.languageDescription': 'Choisissez votre langue préférée',
    'settings.accountSettings': 'Paramètres du Compte',
    'settings.notifications': 'Notifications',
    'settings.emailUpdates': 'Mises à jour par Email',
    'settings.done': 'Terminé',
    'dashboard.title': 'Évaluation de Mains 👀',
    'dashboard.subtitle': 'Avez-vous ce qu\'il faut pour être un mannequin de mains? Découvrons-le.',
    'dashboard.uploadDescription': 'Téléchargez une photo et obtenez une évaluation honnête. Pas de sucre.',
    'dashboard.mobileTips': '📱 Conseils Mobiles:',
    'dashboard.mobileTipsDescription': 'Cliquez sur "Télécharger Photo" pour choisir dans votre galerie ou prendre une nouvelle photo avec votre caméra. Assurez-vous que vos mains sont bien éclairées et clairement visibles!',
    'dashboard.dropPhoto': 'Déposez votre photo ici',
    'dashboard.clickToUpload': 'Cliquez pour télécharger votre photo de mains',
    'dashboard.dragDropOption': 'ou glissez-déposez, ou utilisez le bouton ci-dessous',
    'dashboard.uploadPhoto': 'Télécharger Photo',
    'dashboard.chooseFromGallery': 'Choisir de la Galerie',
    'dashboard.takePhoto': 'Prendre une Photo',
    'dashboard.readyForRating': 'Prêt à obtenir votre évaluation brutalement honnête?',
    'dashboard.analyzing': 'Analyse en cours...',
    'dashboard.generateResults': 'Générer Résultats',
    'dashboard.outOf': 'sur 100',
    'dashboard.analysis': '📝 Analyse',
    'dashboard.strengths': '✨ Forces',
    'dashboard.weaknesses': '⚠️ Faiblesses',
    'dashboard.noStrengths': 'Aucune force identifiée',
    'dashboard.noWeaknesses': 'Aucune faiblesse identifiée',
    'dashboard.tryAnotherPhoto': '📸 Essayer Une Autre Photo',
    'dashboard.pleaseSelectFile': 'Veuillez sélectionner un fichier d\'abord',
    'dashboard.fileSizeError': 'La taille du fichier doit être inférieure à 10MB',
    'dashboard.invalidFileError': 'Veuillez sélectionner un fichier image',
    'dashboard.signinRequired': 'Veuillez vous connecter pour générer des critiques.',
    'dashboard.generationFailed': 'Échec de la génération des résultats. Veuillez réessayer.',
    'profile.dashboard': '🏠 Tableau de Bord',
    'profile.gallery': '🖼️ Galerie',
    'profile.profile': '👤 Profil',
    'profile.settings': '⚙️ Paramètres',
    'profile.logout': '🚪 Déconnexion',
    'gallery.title': 'Votre Galerie',
    'gallery.subtitle': 'Visualisez et gérez votre portefeuille de mannequinat de mains',
    'gallery.loading': 'Chargement de Votre Galerie...',
    'gallery.loadingDescription': 'Récupération de vos critiques de mains',
    'gallery.error': 'Erreur de Chargement de la Galerie',
    'gallery.tryAgain': '🔄 Réessayer',
    'gallery.noPhotos': 'Pas de Photos Encore',
    'gallery.noPhotosDescription': 'Commencez à construire votre portefeuille de mannequinat de mains',
    'gallery.uploadFirst': '🚀 Télécharger Première Photo',
    'profile.title': 'Paramètres de Profil',
    'profile.subtitle': 'Gérez votre compte et préférences',
    'profile.backToDashboard': 'Retour au Tableau de Bord',
    'profile.viewGallery': '🖼️ Voir Galerie',
    'profile.accountInfo': 'Informations du Compte',
    'profile.editProfile': '✏️ Modifier Profil',
    'profile.displayName': 'Nom d\'Affichage',
    'profile.displayNamePlaceholder': 'Entrez votre nom d\'affichage',
    'profile.email': 'E-mail',
    'profile.emailPlaceholder': 'Entrez votre e-mail',
    'profile.accountType': 'Type de Compte',
    'profile.googleAccount': 'Compte Google',
    'profile.emailPassword': 'E-mail et Mot de Passe',
    'profile.notSet': 'Non défini',
    'profile.saving': 'Enregistrement...',
    'profile.saveChanges': '💾 Enregistrer Modifications',
    'profile.cancel': '❌ Annuler',
    'profile.uploadCredits': '📤 Crédits de Téléchargement',
    'profile.uploadsRemaining': 'Téléchargements Restants',
    'profile.uploadsRemainingDesc': 'Téléchargements que vous pouvez utiliser à tout moment',
    'profile.totalUploads': 'Total de Téléchargements Utilisés',
    'profile.totalUploadsDesc': 'Nombre total de téléchargements',
    'profile.dangerZone': '⚠️ Zone de Danger',
    'profile.deleteAccount': 'Supprimer le Compte',
    'profile.deleteAccountDesc': 'Supprimer définitivement votre compte et données',
    'profile.delete': '🗑️ Supprimer',
    'profile.signOut': 'Se Déconnecter',
    'profile.signOutDesc': 'Se déconnecter de tous les appareils',
    'profile.signOutButton': '🚪 Se Déconnecter',
    'offer.title': 'Obtenez Votre Évaluation de Mains',
    'offer.subtitle': 'Évaluation professionnelle de mannequinat de mains',
    'offer.price': 'pour 25 photos',
    'offer.perPicture': 'C\'est seulement $0.60 par photo!',
    'offer.whatYouGet': 'Ce Que Vous Obtenez:',
    'offer.scoreOutOf': 'Score sur 100 pour chaque photo',
    'offer.expertFeedback': 'Commentaires et analyse d\'experts',
    'offer.improvementTips': 'Conseils et suggestions d\'amélioration',
    'offer.verdict': 'Verdict de potentiel de mannequin de mains',
    'offer.unlimitedTime': 'Temps illimité pour utiliser les crédits',
    'offer.processing': 'Traitement...',
    'offer.buyFor': 'Acheter pour $',
    'offer.back': 'Retour',
    'offer.warningTitle': '⚠️',
    'offer.warningMessage': 'Il vous reste 0 téléchargements. Achetez plus de crédits pour continuer.',
    'navbar.dashboard': 'Tableau de Bord',
    'navbar.getCredits': 'Obtenir des Crédits',
    'navbar.signIn': 'Se Connecter',
    'navbar.signUp': 'S\'inscrire',
  }
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { user, updateUserLanguage } = useAuth()
  const [language, setLanguage] = useState<Language>('en')
  const [isLoaded, setIsLoaded] = useState(false)

  // Load language from cloud database (user.language) or localStorage as fallback
  useEffect(() => {
    if (user?.language) {
      // Use language from cloud database
      setLanguage(user.language)
      // Also update localStorage for consistency
      localStorage.setItem('language', user.language)
    } else {
      // Fallback to localStorage if no cloud language
      const savedLanguage = localStorage.getItem('language') as Language
      if (savedLanguage && ['en', 'es', 'fr'].includes(savedLanguage)) {
        setLanguage(savedLanguage)
      }
    }
    setIsLoaded(true)
  }, [user?.language])

  // Save language to both cloud database and localStorage when it changes
  const handleSetLanguage = async (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
    
    // Save to cloud database if user is authenticated
    if (user) {
      try {
        await updateUserLanguage(lang)
      } catch (error) {
        console.error('Failed to save language to cloud:', error)
        // Continue with local storage even if cloud save fails
      }
    }
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  const value = {
    language,
    setLanguage: handleSetLanguage,
    t
  }

  // Don't render until language is loaded to prevent hydration mismatch
  if (!isLoaded) {
    return null
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}
